---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://phar.phpunit.de/phpunit.phar -o phpunit.phar &&
    /bin/mv phpunit.phar {{ phpunit_path }}
    creates="{{ phpunit_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ phpunit_path }}"
