---
- name: check if users are created
  command: >
    /usr/bin/mongo {{ _prefix }} --quiet --eval "db.getSiblingDB('{{ item.0.name }}').system.users.find({user:'{{ item.1.name }}'}).count();"
  changed_when: false
  register: _users
  with_subelements:
    - mongodb_databases
    - users

- name: create users
  command: >
    /usr/bin/mongo {{ _prefix }} --quiet --eval "db.getSiblingDB('{{ item.item.0.name }}').addUser('{{ item.item.1.name }}', '{{ item.item.1.password }}', '{{ item.item.1.read_only }}');"
  notify: restart mongodb
  when: _users.results is defined and item.stdout == "0"
  with_items: _users.results
