---
- name: add gpg key
  apt_key: >
    id="{{ mongodb_key_id }}"
    keyserver="{{ mongodb_key_keyserver }}"
    state=present
  when: mongodb_key_keyserver != false

- name: add repository
  apt_repository: >
    repo="{{ mongodb_repository }}"
    state=present
    update_cache=yes
  when: mongodb_repository != false

- name: install service
  apt: >
    name=mongodb-org-server
    state=present
  notify: restart mongodb

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=mongod
    state=started
