---
- name: install service
  apt: >
    force=yes
    pkg="mongodb-server={{ mongodb_version }}"
    state=present
  notify: restart mongodb

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=mongodb
    state=started

- name: wait for preallocating files
  pause: >
    seconds="{{ mongodb_pause }}"
