---
- name: install service
  apt: >
    force=yes
    pkg=mongodb-server
    state=present
  notify: restart mongodb

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=mongodb
    state=started
