---
- name: "refresh and clear apt-get database for project '{{ project }}' with environment '{{ env }}'"
  gather_facts: false
  hosts: "{{ project }}_{{ env }}"
  roles:
    -
      role: refresh
    -
      role: clear
  sudo: true
