alias ..='cd ..'
alias ...='cd ...'
alias cd..='cd ..'
alias cd...='cd ...'
alias cd-='cd -'
alias cp='cp -i'
alias df='df -h'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --colour=auto'
alias h='history'
alias ln='ln -s'
alias ls='ls --color=auto'
alias mv='mv -i'
alias rm='rm -i'
