---
- name: copy commands
  copy: >
    dest="{{ symfony_remote_path }}{{ item }}"
    group="{{ symfony_commands_group }}"
    mode="0755"
    owner="{{ symfony_commands_user }}"
    src="{{ symfony_files_path }}{{ item }}"
  with_items: "{{ symfony_commands }}"

- name: install bash completion
  shell: >
    /usr/bin/curl -L -s -S https://raw.githubusercontent.com/KnpLabs/symfony2-autocomplete/master/symfony2-autocomplete.bash -o symfony2-autocomplete.bash &&
    /bin/mv symfony2-autocomplete.bash /etc/bash_completion.d/symfony2
    creates=/etc/bash_completion.d/symfony2

- name: set file permissions
  file: >
    group=root
    mode="0644"
    owner=root
    path=/etc/bash_completion.d/symfony2

- name: add lines to global profile
  lineinfile: >
    create=yes
    dest=/etc/profile.d/symfony.sh
    group=root
    insertafter=EOF
    line="{{ item }}"
    mode="0644"
    owner=root
    state=present
  with_items: "{{ symfony_settings }}"

- name: add service to init.d
  template: >
    dest="/etc/init.d/{{ item }}"
    group=root
    mode="0755"
    owner=root
    src="{{ symfony_files_path }}{{ item }}"
  with_items: "{{ symfony_services }}"

- name: run update-rc.d defaults
  command: >
    /usr/sbin/update-rc.d {{ item }} defaults
  changed_when: false
  with_items: "{{ symfony_services }}"

- name: run update-rc.d enable
  command: >
    /usr/sbin/update-rc.d {{ item }} enable
  changed_when: false
  with_items: "{{ symfony_services }}"

- name: run init.d
  command: >
    /etc/init.d/{{ item }}
  changed_when: false
  with_items: "{{ symfony_services }}"
