---
- name: install modules
  apt: >
    force=yes
    pkg="{{ item }}"
    state=present
  with_items: "{{ vagrant_modules }}"

- name: install sudoers parameters
  shell: >
    /usr/bin/curl -sS https://raw.githubusercontent.com/mitchellh/vagrant/master/contrib/sudoers/linux-ubuntu -o vagrant &&
    /bin/mv vagrant {{ vagrant_sudoers_path }}/
    creates="{{ vagrant_sudoers_path }}/vagrant"

- name: set file permissions
  file: >
    group=root
    mode="0440"
    owner=root
    path="{{ vagrant_sudoers_path }}/vagrant"

- name: set fixed port for rpc.mountd
  lineinfile: >
    dest=/etc/default/nfs-kernel-server
    line="RPCMOUNTDOPTS=\"-p {{ vagrant_rpc_mountd_port }}\""
    regexp="RPCMOUNTDOPTS="
    state=present
  notify: restart nfs-kernel-server
  when: vagrant_rpc_mountd_port != false

- name: set deny hosts
  lineinfile: >
    dest=/etc/hosts.deny
    insertafter=EOF
    line="{{ item }}"
    state=present
  with_items: "{{ vagrant_deny_hosts }}"

- name: set allow hosts
  lineinfile: >
    dest=/etc/hosts.allow
    insertafter=EOF
    line="{{ item }}"
    state=present
  with_items: "{{ vagrant_allow_hosts }}"

- name: disable nfs-kernel-server autostart
  lineinfile: >
    dest=/etc/init.d/nfs-kernel-server
    line="# {{ item.key }}: {{ item.value }}"
    regexp="^# {{ item.key }}: "
    state=present
  register: _nfs_kernel_server
  with_dict: "{{ vagrant_nfs_lines }}"

- name: run update-rc.d disable
  command: >
    /usr/sbin/update-rc.d nfs-kernel-server disable
  when: _nfs_kernel_server.changed == true
