---
- name: include os specific variables
  include_vars: >
    {{ item }}
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "defaults.yml"
      paths:
       - ../vars/
  when: vagrant_repository is undefined
