---
# it must be there, because: can't have more than one mta
- name: uninstall other services
  apt: >
    force=yes
    name="{{ item }}"
    purge=yes
    state=absent
  with_items: "{{ postfix_alternatives }}"
