---
# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: set max user watches
  lineinfile: >
    create=yes
    dest=/etc/sysctl.d/60-user.conf
    group=root
    line="fs.inotify.max_user_watches = 524288"
    mode="0644"
    owner=root
    regexp="^fs.inotify.max_user_watches"
    state=present

# https://confluence.jetbrains.com/display/IDEADEV/Inotify+Instances+Limit
- name: set max user instances
  lineinfile: >
    create=yes
    dest=/etc/sysctl.d/60-user.conf
    group=root
    line="fs.inotify.max_user_instances = 256"
    mode="0644"
    owner=root
    regexp="^fs.inotify.max_user_instances"
    state=present
