---
- name: install service
  apt: >
    pkg=cron
    state=present
  notify: restart cron

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=cron
    state=started
