---
- name: include os specific variables
  include_vars: >
    {{ item }}
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ nodejs_version }}.yml"
      - "defaults.yml"
      paths:
       - ../vars/
  when: nodejs_repository is undefined
