#!/bin/bash
### BEGIN INIT INFO
# Provides:          symfony_projectx
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Setting up Symfony2 environment
# Description:       Setting up Symfony2 environment
### END INIT INFO

PROJECT_NAME="projectx"

case "$1" in
  start)
    echo "Setting up Symfony2 environment ..."

    mkdir -p /var/lock/cron/${PROJECT_NAME}
    mkdir -p /var/log/cron/${PROJECT_NAME}
    mkdir -p /var/log/queue/${PROJECT_NAME}

    find /var/lock/cron -type d -exec chmod 0777 {} \;
    find /var/log/cron -type d -exec chmod 0777 {} \;
    find /var/log/queue -type d -exec chmod 0777 {} \;

    echo "Done."
    ;;
  *)
    echo "Usage: /etc/init.d/symfony_projectx start"
    exit 1
    ;;
esac

exit 0
