---
- name: include os specific variables
  include_vars: >
    {{ item }}
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "os-defaults.yml"
      paths:
       - ../vars/
  when: rabbitmq_repository is undefined
