---
- name: include os specific variables
  include_vars: >
    "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - default.yml
      paths:
       - ../vars/
