---
- name: add gpg key
  apt_key: >
    id="{{ rabbitmq_key_id }}"
    state=present
    url="{{ rabbitmq_key_url }}"
  when: rabbitmq_key_url != false

- name: add repository
  apt_repository: >
    repo="{{ rabbitmq_repository }}"
    state=present
    update_cache=yes
  when: rabbitmq_repository != false

- name: install service
  apt: >
    name=rabbitmq-server
    state=present
  notify: restart rabbitmq

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=rabbitmq-server
    state=started
