---
- include: include_vars.yml

- include: install.yml

- include: secure.yml

- include: configure.yml

- include: plugins_rabbitmq_management.yml
  when: "'rabbitmq_management' in rabbitmq_plugins"
