---
- include_tasks: include_vars.yml

- include_tasks: install.yml

- include_tasks: secure.yml

- include_tasks: configure.yml

- include_tasks: plugins_rabbitmq_management.yml
  when: "'rabbitmq_management' in rabbitmq_plugins"
