---
- name: create dir for config files
  file: >
    group="{{ item.group }}"
    mode="0755"
    owner="{{ item.name }}"
    path="{{ item.home }}/.phpmd"
    state=directory
  with_items: phpmd_users

- name: copy configs
  template: >
    dest="{{ item.0.home }}/.phpmd/{{ item.1 }}"
    force=yes
    group="{{ item.0.group }}"
    mode="0600"
    owner="{{ item.0.name }}"
    src="{{ phpmd_files_path }}{{ item.1 }}"
  with_subelements:
    - phpmd_users
    - configs

