---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://phar.phpunit.de/phpdcd.phar -o phpdcd.phar &&
    /bin/mv phpdcd.phar {{ phpdcd_path }}
    creates="{{ phpdcd_path }}"

- name: allow everyone for selfupdate
  file: >
    group="{{ phpdcd_commands_group }}"
    mode="0777"
    owner="{{ phpdcd_commands_user }}"
    path="{{ phpdcd_path }}"
