---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://phar.phpunit.de/phpdcd.phar -o phpdcd.phar &&
    /bin/mv phpdcd.phar {{ phpdcd_path }}
    creates="{{ phpdcd_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ phpdcd_path }}"
