---
- name: install package
  package: >
    name=p7zip-full
    state=present

- name: install post-packages
  package: >
    name="{{ item }}"
    state=present
  with_items: "{{ p7zip_post_packages }}"
