---
- name: install package
  apt: >
    force=yes
    pkg=p7zip-full
    state=present

- name: install post-packages
  apt: >
    force=yes
    pkg="{{ item }}"
    state=present
  with_items: p7zip_post_packages
