---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://phar.phpunit.de/phpcpd.phar -o phpcpd.phar &&
    /bin/mv phpcpd.phar {{ phpcpd_path }}
    creates="{{ phpcpd_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ phpcpd_path }}"
