---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://phar.phpunit.de/phploc.phar -o phploc.phar &&
    /bin/mv phploc.phar {{ phploc_path }}
    creates="{{ phploc_path }}"

- name: allow everyone for selfupdate
  file: >
    group="{{ phploc_commands_group }}"
    mode="0777"
    owner="{{ phploc_commands_user }}"
    path="{{ phploc_path }}"
