---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S {{ robomongo_url }} -o robomongo.deb &&
    /usr/bin/dpkg -i robomongo.deb &&
    /bin/rm robomongo.deb
    creates="{{ robomongo_robomongo_path }}"
  when: robomongo_url != false
