---
- name: check if databases are created
  command: >
    /usr/bin/mysql {{ _prefix }} --batch --skip-column-names -e "SHOW DATABASES LIKE '{{ item.name }}';"
  changed_when: false
  register: _databases
  when: item.name != "*"
  with_items: mysql_databases

- name: create databases
  command: >
    /usr/bin/mysql {{ _prefix }} -e "CREATE DATABASE {{ item.item.name }};"
  when: _databases.results is defined and item.stdout == ""
  with_items: _databases.results

- name: check if users are created
  command: >
    /usr/bin/mysql {{ _prefix }} --batch --skip-column-names -e "SELECT DISTINCT User FROM mysql.user WHERE User LIKE '{{ item.1.name }}';"
  changed_when: false
  register: _users
  with_subelements:
    - mysql_databases
    - users

- name: create users
  command: >
    /usr/bin/mysql {{ _prefix }} -e "GRANT USAGE ON *.* TO '{{ item.item.1.name }}'@'{{ item.item.1.host }}' IDENTIFIED BY '{{ item.item.1.password }}';"
  notify: flush privileges
  when: _users.results is defined and item.stdout == ""
  with_items: _users.results

- name: create privileges
  command: >
    /usr/bin/mysql {{ _prefix }} -e "GRANT {{ item.item.1.priv }} ON {{ item.item.0.name }}.* TO '{{ item.item.1.name }}'@'{{ item.item.1.host }}';"
  notify: flush privileges
  when: _users.results is defined and item.stdout == ""
  with_items: _users.results
