---
- name: add gpg key
  apt_key: >
    id="{{ mysql_key_id }}"
    state=present
    url="{{ mysql_key_url }}"
  when: mysql_key_url != false

- name: add repository
  apt_repository: >
    repo="{{ mysql_repository }}"
    state=present
    update_cache=yes
  when: mysql_repository != false

- name: set debconf variables
  debconf: >
    name=mysql-server
    question="{{ item }}"
    value="{{ mysql_login_password }}"
    vtype=password
  changed_when: false
  when: ansible_os_family == "Debian"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again

- name: install service
  package: >
    name="{{ mysql_package }}"
    state=present
  notify: restart mysql
  when: mysql_package != false

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=mysql
    state=started
  when: ansible_os_family == "Debian"
