---
- name: install tool
  shell: >
    /usr/bin/curl -sS http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar &&
    /bin/mv php-cs-fixer.phar {{ php_cs_fixer_path }}
    creates="{{ php_cs_fixer_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ php_cs_fixer_path }}"
