---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar &&
    /bin/mv php-cs-fixer.phar {{ php_cs_fixer_path }}
    creates="{{ php_cs_fixer_path }}"

- name: allow everyone for selfupdate
  file: >
    group="{{ php_cs_fixer_commands_group }}"
    mode="0777"
    owner="{{ php_cs_fixer_commands_user }}"
    path="{{ php_cs_fixer_path }}"
