---
- name: add beta repository
  apt_repository: >
    repo="{{ opera_beta_repository }}"
    state=present
    update_cache=yes
  when: opera_beta_repository != false

- name: install beta package
  apt: >
    name=opera-beta
    state=present
