---
- name: add repository
  apt_repository: >
    repo=ppa:indicator-multiload/stable-daily
    state=present
    update_cache=yes

- name: install package
  apt: >
    force=yes
    pkg=indicator-multiload
    state=present
