---
- name: add repository
  apt_repository: >
    repo=ppa:indicator-multiload/stable-daily
    state=present
    update_cache=yes

- name: install package
  apt: >
    name=indicator-multiload
    state=present
