---
- name: add gpg key
  apt_key: >
    id="{{ java_key_id }}"
    keyserver="{{ java_key_keyserver }}"
    state=present
  when: java_key_keyserver != false

- name: set debconf variables
  debconf: >
    name="oracle-java{{ java_version }}-installer"
    question=shared/accepted-oracle-license-v1-1
    value=true
    vtype=select
  changed_when: false

- name: add repositories
  apt_repository: >
    repo="{{ java_repository }}"
    state=present
    update_cache=yes
  when: java_repository != false

- name: install package
  apt: >
    name="oracle-java{{ java_version }}-installer"
    state=present
