---
- name: add repositories
  apt_repository: >
    repo="{{ item }}"
    state=present
    update_cache=yes
  with_items: "{{ macbuntu_repositories }}"

- name: install pre-packages
  apt: >
    name="{{ item }}"
    state=present
  with_items: "{{ macbuntu_pre_packages }}"

- name: install packages
  apt: >
    name="{{ item }}"
    state=present
  with_items: "{{ macbuntu_packages }}"

- name: install post-packages
  apt: >
    name="{{ item }}"
    state=present
  with_items: "{{ macbuntu_post_packages }}"
