---
- name: add repository (apt)
  apt_repository: >
    repo=ppa:ansible/ansible
    state=present
    update_cache=yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: install package (apt)
  apt: >
    force=yes
    pkg=ansible
    state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: install package (homebrew)
  homebrew: >
    name=ansible
    state=present
  when: ansible_distribution == "MacOSX"
