---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S http://static.pdepend.org/php/{{ pdepend_version }}/pdepend.phar -o pdepend.phar &&
    /bin/mv pdepend.phar {{ pdepend_path }}
    creates="{{ pdepend_path }}"

- name: allow everyone for selfupdate
  file: >
    group="{{ pdepend_commands_group }}"
    mode="0777"
    owner="{{ pdepend_commands_user }}"
    path="{{ pdepend_path }}"
