---
- name: install service
  apt: >
    name=fail2ban
    state=present
  notify: restart fail2ban

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=fail2ban
    state=started
