---
wkhtmltox_pre_packages:
  - fontconfig
  - libc6
  - libfontconfig1
  - libfreetype6
  - libjpeg-turbo8
  - libpng12-0
  - libssl1.0.0
  - libstdc++6
  - libx11-6
  - libxext6
  - libxrender1
  - zlib1g
wkhtmltox_wkhtmltopdf_path: /usr/local/bin/wkhtmltopdf
