---
- name: add repository
  apt_repository: >
    repo=ppa:alexmurray/indicator-sensors
    state=present
    update_cache=yes

- name: install package
  apt: >
    name=indicator-sensors
    state=present
