---
- name: install package
  package: >
    name=heroku/brew/heroku
    state=present

- name: enable plugins
  shell: >
    heroku plugins | grep -q {{ item }} || heroku plugins:install {{ item }}
  changed_when: "_plugins.rc == 0 and 'installed' in _plugins.stderr"
  failed_when: "_plugins.rc != 0"
  register: _plugins
  with_items: "{{ heroku_plugins }}"
