---
- name: install package
  package: >
    name=heroku
    state=present

- name: enable plugins
  shell: >
    heroku plugins:install {{ item }}
  changed_when: false
  with_items: "{{ heroku_plugins }}"
