---
- name: install required libraries
  package: >
    name="{{ item }}"
    state=present
  with_items: "{{ common_required_libraries }}"

- name: install required packages
  package: >
    name="{{ item }}"
    state=present
  with_items: "{{ common_required_packages }}"
