---
- name: install required libraries (apt)
  apt: >
    force=yes
    pkg="{{ item }}"
    state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  with_items: common_required_libraries

- name: install required packages (apt)
  apt: >
    force=yes
    pkg="{{ item }}"
    state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  with_items: common_required_packages
