---
- name: install tool
  shell: >
    /usr/bin/curl -sS http://static.pdepend.org/php/{{ pdepend_version }}/pdepend.phar -o pdepend.phar &&
    /bin/mv pdepend.phar {{ pdepend_path }}
    creates="{{ pdepend_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ pdepend_path }}"
