---
- name: install tool
  shell: >
    /usr/bin/curl -L -s -S https://getcomposer.org/installer | /usr/bin/php &&
    /bin/mv composer.phar {{ composer_path }}
    creates="{{ composer_path }}"

- name: allow everyone for selfupdate
  file: >
    group="{{ composer_commands_group }}"
    mode="0777"
    owner="{{ composer_commands_user }}"
    path="{{ composer_path }}"
