---
- name: install tool
  shell: >
    /usr/bin/curl -sS https://getcomposer.org/installer | /usr/bin/php &&
    /bin/mv composer.phar {{ composer_path }}
    creates="{{ composer_path }}"

- name: allow everyone for selfupdate
  file: >
    group=root
    mode="0777"
    owner=root
    path="{{ composer_path }}"
