---
- name: add repository
  apt_repository: >
    repo=ppa:fingerprint/fingerprint-gui
    state=present
    update_cache=yes

- name: install pre-packages
  apt: >
    force=yes
    pkg="{{ item }}"
    state=present
  with_items: fingerprint_gui_pre_packages

- name: install package
  apt: >
    force=yes
    pkg=fingerprint-gui
    state=present
