---
- name: add repository
  apt_repository: >
    repo=ppa:fingerprint/fingerprint-gui
    state=present
    update_cache=yes

# @FIX: problem with first login after boot, see:
# http://home.ullrich-online.cc/fingerprint/Forum/topic.php?TopicId=491
- name: add experimental repository
  apt_repository: >
    repo=ppa:fingerprint/fingerprint-gui-experimental
    state=present
    update_cache=yes
  when: fingerprint_fix_login_issue == true

- name: install pre-packages
  apt: >
    name="{{ item }}"
    state=present
  with_items: "{{ fingerprint_gui_pre_packages }}"

- name: install package
  apt: >
    name=fingerprint-gui
    state=present
