---
- name: restart mysql
  service: >
    name=mysql
    state=restarted
  when: ansible_os_family == "Debian"

- name: flush privileges
  command: >
    /usr/bin/mysql {{ _prefix }} -e "FLUSH PRIVILEGES;"
  changed_when: false
