---
macbuntu_packages:
  - macbuntu-os-icons-lts-v7
  - macbuntu-os-ithemes-lts-v7
macbuntu_post_packages: []
#  - faenza-icon-theme
macbuntu_pre_packages:
  - libglib2.0-bin
macbuntu_repositories:
  - ppa:noobslab/macbuntu
