---
# custom parameters
_common_required_libraries:
  - aptitude
  - debconf
  - debconf-utils
  - python-apt
_common_required_packages:
  - apt-transport-https
  - curl
  - python-software-properties
  - software-properties-common
_common_sources_repositories:
  - deb http://archive.ubuntu.com/ubuntu trusty multiverse
  - deb-src http://archive.ubuntu.com/ubuntu trusty multiverse

  - deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse
  - deb-src http://archive.ubuntu.com/ubuntu trusty-updates multiverse

  - deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse
  - deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse

  - deb http://archive.canonical.com/ubuntu trusty partner
  - deb-src http://archive.canonical.com/ubuntu trusty partner


  - deb http://security.ubuntu.com/ubuntu trusty-security multiverse
  - deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse
