---
- name: install service
  apt: >
    pkg=memcached
    state=present
  notify: restart memcached

- name: ensure a service is enabled and running
  service: >
    enabled=yes
    name=memcached
    state=started
