---
- name: create dir for config files
  file: >
    group="{{ item.0.group }}"
    mode="0755"
    owner="{{ item.0.name }}"
    path="{{ item.0.home }}/.rsync"
    state=directory
  with_subelements:
    - rsync_users
    - configs

- name: copy configs
  copy: >
    dest="{{ item.0.home }}/.rsync/{{ item.1 }}"
    group="{{ item.0.group }}"
    mode="0644"
    owner="{{ item.0.name }}"
    src="{{ rsync_files_path }}{{ item.1 }}"
  with_subelements:
    - rsync_users
    - configs
