---
- name: "install '{{ name }}' pre-packages"
  homebrew: >
    name="{{ item }}"
    state=present
  with_items: "{{ pre }}"

- name: "install '{{ name }}' package"
  homebrew: >
    name="{{ name }}"
    state=present

- name: "install '{{ name }}' post-packages"
  homebrew: >
    name="{{ item }}"
    state=present
  with_items: "{{ post }}"
