---
- name: "install '{{ name }}' pre-packages"
  homebrew: >
    name="{{ item }}"
    state=present
  sudo: false
  with_items: pre

- name: "install '{{ name }}' package"
  homebrew: >
    name="{{ name }}"
    state=present
  sudo: false

- name: "install '{{ name }}' post-packages"
  homebrew: >
    name="{{ item }}"
    state=present
  sudo: false
  with_items: post
